<?php
require_once 'inc.byochu.php';

// m_tekiyo テーブルが更新されていれば「農水省農薬登録情報提供システム／病害虫で探す」ページを読み込んで byochu.txt 作成
if (!$finfo && !$fupdate) {
  if ($debug) echo "acis: byochu: Not Modified\n";
  return 0;
}
$time = -microtime(true);
$s = file_get_contents("$dopage/$dofile/");
if ($s === false) {
  logputs('acis: byochu', "Cannot Load $dofile");
  if ($debug) echo "acis: byochu: Cannot Load $dofile\n";
  return 0;
}

/* 病害虫・雑草名称絞込み HTML -> SQL 変換 */
// 前処理
$date = date('Y.m.d');
$s = preg_replace('/.*const pestsListJson ?= ?\[/s', '[', $s);
$s = preg_replace('/(.*?\]);.*/s', '$1', $s);
$s = mb_convert_kana($s, 'asKV', 'utf8');
$pestslist = json_decode($s, true);
$query = <<<BYOCHU1
--/d
/* $date 現在の農水省農薬登録情報提供システムに基づく病害虫 ID テンポラリマスター (2025.10.17) */
begin transaction;
drop table if exists $idtbl;
create temp table $idtbl (cid integer, gid integer, idbyochu varchar primary key, byochu varchar);\n
BYOCHU1;
foreach($pestslist as $pest) {
  if (substr($pest['pestsName'], -1, 1) == 'G') continue;
  $code = $pest['pestsWeedCode'];
  if ($code[0] == '0') $code[0] = '3';
  $query .= sprintf("insert or ignore into $idtbl values(%d, %d, '%s', '%s');\n", $code[0], substr($code, 1, 3), $code, $pest['pestsName']);
}
$query .= <<<BYOCHU2
commit;
begin transaction;
drop table if exists $tmptbl;
create temp table $tmptbl (cid integer, gid integer, idbyochu varchar, byochu varchar unique, betsumei);
insert into $tmptbl select cid, gid, idbyochu, byochu, strconv(byochu, 'k') from m_tekiyo left join $idtbl using(byochu) where ifnullstr(byochu, '-') <> '-' group by byochu order by idbyochu;
drop table if exists $idtbl;
create temp table $idtbl (idbyochu integer primary key autoincrement, byochu varchar unique);
insert or ignore into $idtbl (byochu) select mokuteki from m_tekiyo where ifnullstr(mokuteki, '-') <> '-' group by mokuteki;
insert or ignore into $tmptbl (cid, gid, idbyochu, byochu, betsumei) select 5, 0, idbyochu + 50000000, byochu, strconv(byochu, 'k') from $idtbl;
drop table if exists $idtbl;
--ふりがな優先処理1
update $tmptbl set betsumei = replace(betsumei, '腐敗', 'ふはい') where byochu like '%腐敗%';
update $tmptbl set betsumei = replace(betsumei, '球根', 'きゅうこん') where byochu like '%球根%';
update $tmptbl set betsumei = replace(betsumei, '叢根', 'そうこん') where byochu like '%叢根%';
update $tmptbl set betsumei = replace(betsumei, '発根', 'はっこん') where byochu like '%発根%';
update $tmptbl set betsumei = replace(betsumei, '種子', 'しゅし') where byochu like '%種子%';
update $tmptbl set betsumei = replace(betsumei, '枯死', 'こし') where byochu like '%枯死%';
update $tmptbl set betsumei = replace(betsumei, '枯込', 'かれこみ') where byochu like '%枯込%';
update $tmptbl set betsumei = replace(betsumei, '広葉', 'こうよう') where byochu like '%広葉%';
update $tmptbl set betsumei = replace(betsumei, '落葉', 'らくよう') where byochu like '%落葉%';
update $tmptbl set betsumei = replace(betsumei, '葉鞘', 'ようしょう') where byochu like '%葉鞘%';
update $tmptbl set betsumei = replace(betsumei, '開花', 'かいか') where byochu like '%開花%';
update $tmptbl set betsumei = replace(betsumei, '花蕾', 'からい') where byochu like '%花蕾%';
update $tmptbl set betsumei = replace(betsumei, '越冬', 'えっとう') where byochu like '%越冬%';
update $tmptbl set betsumei = replace(betsumei, '先端', 'せんたん') where byochu like '%先端%';
update $tmptbl set betsumei = replace(betsumei, '亀裂', 'きれつ') where byochu like '%亀裂%';
update $tmptbl set betsumei = replace(betsumei, '炭疽', 'たんそ') where byochu like '%炭疽%';
update $tmptbl set betsumei = replace(betsumei, '白絹', 'しらきぬ') where byochu like '%白絹%';
update $tmptbl set betsumei = replace(betsumei, '赤衣', 'あかごろも') where byochu like '%赤衣%';
update $tmptbl set betsumei = replace(betsumei, '野火', 'のび') where byochu like '%野火%';
update $tmptbl set betsumei = replace(betsumei, '雲形', 'くもがた') where byochu like '%雲形%';
update $tmptbl set betsumei = replace(betsumei, '陥没', 'かんぼつ') where byochu like '%陥没%';
update $tmptbl set betsumei = replace(betsumei, '新梢', 'しんしょう') where byochu like '%新梢%';
update $tmptbl set betsumei = replace(betsumei, '梢枯', 'しょうこ') where byochu like '%梢枯%';
update $tmptbl set betsumei = replace(betsumei, '粉状', 'ふんじょう') where byochu like '%粉状%';
update $tmptbl set betsumei = replace(betsumei, '温州', 'うんしゅう') where byochu like '%温州%';
update $tmptbl set betsumei = replace(betsumei, '象の足跡', 'ぞうのあしあと') where byochu like '%象の足跡%';
update $tmptbl set betsumei = replace(betsumei, '疑似', 'ぎじ') where byochu like '%疑似%';
update $tmptbl set betsumei = replace(betsumei, '休眠', 'きゅうみん') where byochu like '%休眠%';
update $tmptbl set betsumei = replace(betsumei, '貯蔵', 'ちょぞう') where byochu like '%貯蔵%';
update $tmptbl set betsumei = replace(betsumei, '貯穀', 'ちょこく') where byochu like '%貯穀%';
update $tmptbl set betsumei = replace(betsumei, '世代', 'せだい') where byochu like '%世代%';
update $tmptbl set betsumei = replace(betsumei, '糞塚', 'ふんづか') where byochu like '%糞塚%';
update $tmptbl set betsumei = replace(betsumei, '散布', 'さんぷ') where byochu like '%散布%';
update $tmptbl set betsumei = replace(betsumei, '防止', 'ぼうし') where byochu like '%防止%';
update $tmptbl set betsumei = replace(betsumei, '軽減', 'けいげん') where byochu like '%軽減%';
update $tmptbl set betsumei = replace(betsumei, '抑制', 'よくせい') where byochu like '%抑制%';
update $tmptbl set betsumei = replace(betsumei, '促進', 'そくしん') where byochu like '%促進%';
update $tmptbl set betsumei = replace(betsumei, '安定', 'あんてい') where byochu like '%安定%';
update $tmptbl set betsumei = replace(betsumei, '向上', 'こうじょう') where byochu like '%向上%';
update $tmptbl set betsumei = replace(betsumei, '覚醒', 'かくせい') where byochu like '%覚醒%';
update $tmptbl set betsumei = replace(betsumei, '倒伏', 'とうふく') where byochu like '%倒伏%';
update $tmptbl set betsumei = replace(betsumei, '節間', 'せっかん') where byochu like '%節間%';
update $tmptbl set betsumei = replace(betsumei, '伸長', 'しんちょう') where byochu like '%伸長%';
update $tmptbl set betsumei = replace(betsumei, '歩合', 'ぶあい') where byochu like '%歩合%';
update $tmptbl set betsumei = replace(betsumei, '普通', 'ふつう') where byochu like '%普通%';
update $tmptbl set betsumei = replace(betsumei, '栽培', 'さいばい') where byochu like '%栽培%';
update $tmptbl set betsumei = replace(betsumei, '表層', 'ひょうそう') where byochu like '%表層%';
update $tmptbl set betsumei = replace(betsumei, '下草', 'したくさ') where byochu like '%下草%';
update $tmptbl set betsumei = replace(betsumei, '樹園', 'じゅえん') where byochu like '%樹園%';
update $tmptbl set betsumei = replace(betsumei, '間伐', 'かんばつ') where byochu like '%間伐%';
update $tmptbl set betsumei = replace(betsumei, '雑かん木', 'ざつかんぼく') where byochu like '%雑かん木%';
update $tmptbl set betsumei = replace(betsumei, '以西', 'いせい') where byochu like '%以西%';
update $tmptbl set betsumei = replace(betsumei, '以外', 'いがい') where byochu like '%以外%';
update $tmptbl set betsumei = replace(betsumei, '北海道', 'ほっかいどう') where byochu like '%北海道%';
update $tmptbl set betsumei = replace(betsumei, '近畿', 'きんき') where byochu like '%近畿%';
update $tmptbl set betsumei = replace(betsumei, '九州', 'きゅうしゅう') where byochu like '%九州%';
update $tmptbl set betsumei = replace(betsumei, '四国', 'しこく') where byochu like '%四国%';
update $tmptbl set betsumei = replace(betsumei, '防除', 'ぼうじょ') where byochu like '%防除%';
update $tmptbl set betsumei = replace(betsumei, '発生', 'はっせい') where byochu like '%発生%';
update $tmptbl set betsumei = replace(betsumei, '芽数', 'めかず') where byochu like '%芽数%';
update $tmptbl set betsumei = replace(betsumei, '根数', 'こんすう') where byochu like '%根数%';
update $tmptbl set betsumei = replace(betsumei, '根量', 'こんりょう') where byochu like '%根量%';
update $tmptbl set betsumei = replace(betsumei, '根長', 'こんちょう') where byochu like '%根長%';
update $tmptbl set betsumei = replace(betsumei, '増加', 'ぞうか') where byochu like '%増加%';
update $tmptbl set betsumei = replace(betsumei, '処理', 'しょり') where byochu like '%処理%';
update $tmptbl set betsumei = replace(betsumei, '適期', 'てっき') where byochu like '%適期%';
update $tmptbl set betsumei = replace(betsumei, '拡大', 'かくだい') where byochu like '%拡大%';
update $tmptbl set betsumei = replace(betsumei, '肥大', 'ひだい') where byochu like '%肥大%';
update $tmptbl set betsumei = replace(betsumei, '落ち', 'おち') where byochu like '%落ち%';
update $tmptbl set betsumei = replace(betsumei, '落果', 'らっか') where byochu like '%落果%';
update $tmptbl set betsumei = replace(betsumei, '着果', 'ちゃっか') where byochu like '%着果%';
update $tmptbl set betsumei = replace(betsumei, '結果', 'けっか') where byochu like '%結果%';
update $tmptbl set betsumei = replace(betsumei, '殺菌', 'さっきん') where byochu like '%殺菌%';
update $tmptbl set betsumei = replace(betsumei, '枯殺', 'こさつ') where byochu like '%枯殺%';
update $tmptbl set betsumei = replace(betsumei, '枯凋', 'こちょう') where byochu like '%枯凋%';
update $tmptbl set betsumei = replace(betsumei, '育苗', 'いくびょう') where byochu like '%育苗%';
update $tmptbl set betsumei = replace(betsumei, '健苗', 'けんびょう') where byochu like '%健苗%';
update $tmptbl set betsumei = replace(betsumei, '徒長', 'とちょう') where byochu like '%徒長%';
update $tmptbl set betsumei = replace(betsumei, '草丈', 'くさたけ') where byochu like '%草丈%';
update $tmptbl set betsumei = replace(betsumei, '花丈', 'はなたけ') where byochu like '%花丈%';
update $tmptbl set betsumei = replace(betsumei, '果皮', 'かひ') where byochu like '%果皮%';
update $tmptbl set betsumei = replace(betsumei, '表皮', 'ひょうひ') where byochu like '%表皮%';
update $tmptbl set betsumei = replace(betsumei, '緑色', 'りょくしょく') where byochu like '%緑色%';
update $tmptbl set betsumei = replace(betsumei, '維持', 'いじ') where byochu like '%維持%';
update $tmptbl set betsumei = replace(betsumei, '打破', 'だは') where byochu like '%打破%';
update $tmptbl set betsumei = replace(betsumei, '側枝', 'そくし') where byochu like '%側枝%';
update $tmptbl set betsumei = replace(betsumei, '側芽', 'そくが') where byochu like '%側芽%';
update $tmptbl set betsumei = replace(betsumei, '腋芽', 'えきが') where byochu like '%腋芽%';
update $tmptbl set betsumei = replace(betsumei, '萌芽', 'ほうが') where byochu like '%萌芽%';
update $tmptbl set betsumei = replace(betsumei, '発芽', 'はつが') where byochu like '%発芽%';
update $tmptbl set betsumei = replace(betsumei, '発生', 'はっせい') where byochu like '%発生%';
update $tmptbl set betsumei = replace(betsumei, '摘葉', 'てきよう') where byochu like '%摘葉%';
update $tmptbl set betsumei = replace(betsumei, '茎葉', 'けいよう') where byochu like '%茎葉%';
update $tmptbl set betsumei = replace(betsumei, '茎稈', 'けいかん') where byochu like '%茎稈%';
update $tmptbl set betsumei = replace(betsumei, '稈長', 'かんちょう') where byochu like '%稈長%';
update $tmptbl set betsumei = replace(betsumei, '小型', 'こがた') where byochu like '%小型%';
update $tmptbl set betsumei = replace(betsumei, '後期', 'こうき') where byochu like '%後期%';
update $tmptbl set betsumei = replace(betsumei, '刈込', 'かりこ') where byochu like '%刈込み%';
update $tmptbl set betsumei = replace(betsumei, '刈込', 'かりこみ') where byochu like '%刈込%';
update $tmptbl set betsumei = replace(betsumei, '整枝', 'せいし') where byochu like '%整枝%';
update $tmptbl set betsumei = replace(betsumei, '分枝', 'ぶんし') where byochu like '%分枝%';
update $tmptbl set betsumei = replace(betsumei, '母枝', 'ぼし') where byochu like '%母枝%';
update $tmptbl set betsumei = replace(betsumei, '使用', 'しよう') where byochu like '%使用%';
update $tmptbl set betsumei = replace(betsumei, '場合', 'ばあい') where byochu like '%場合%';
update $tmptbl set betsumei = replace(betsumei, '間引', 'まび') where byochu like '%間引き%';
update $tmptbl set betsumei = replace(betsumei, '間引', 'まびき') where byochu like '%間引%';
update $tmptbl set betsumei = replace(betsumei, '夏期', 'かき') where byochu like '%夏期%';
update $tmptbl set betsumei = replace(betsumei, '夏秋', 'かしゅう') where byochu like '%夏秋%';
update $tmptbl set betsumei = replace(betsumei, '樹勢', 'じゅせい') where byochu like '%樹勢%';
update $tmptbl set betsumei = replace(betsumei, '葉柄', 'ようへい') where byochu like '%葉柄%';
update $tmptbl set betsumei = replace(betsumei, '振い', 'ぶるい') where byochu like '%振い%';
update $tmptbl set betsumei = replace(betsumei, '忌避', 'きひ') where byochu like '%忌避%';
update $tmptbl set betsumei = replace(betsumei, '出穂', 'しゅっすい') where byochu like '%出穂%';
update $tmptbl set betsumei = replace(betsumei, '蔓延', 'まんえん') where byochu like '%蔓延%';
update $tmptbl set betsumei = replace(betsumei, '木', 'き') where byochu like '%さし木%';
update $tmptbl set betsumei = replace(betsumei, '挿し木', 'さしき') where byochu like '%挿し木%';
update $tmptbl set betsumei = replace(betsumei, '挿木', 'さしき') where byochu like '%挿木%';
update $tmptbl set betsumei = replace(betsumei, '挿苗', 'さしなえ') where byochu like '%挿苗%';
update $tmptbl set betsumei = replace(betsumei, '予措', 'よそ') where byochu like '%予措%';
update $tmptbl set betsumei = replace(betsumei, '噴霧', 'ふんむ') where byochu like '%噴霧%';
update $tmptbl set betsumei = replace(betsumei, '漂流', 'ひょうりゅう') where byochu like '%漂流%';
update $tmptbl set betsumei = replace(betsumei, '高接', 'たかつぎ') where byochu like '%高接%';
update $tmptbl set betsumei = replace(betsumei, '張芝', 'はりしば') where byochu like '%張芝%';
update $tmptbl set betsumei = replace(betsumei, '雄花', 'おばな') where byochu like '%雄花%';
update $tmptbl set betsumei = replace(betsumei, '雌花', 'めばな') where byochu like '%雌花%';
update $tmptbl set betsumei = replace(betsumei, '鉢花', 'はちばな') where byochu like '%鉢花%';
update $tmptbl set betsumei = replace(betsumei, '花成', 'かせい') where byochu like '%花成%';
update $tmptbl set betsumei = replace(betsumei, '体系', 'たいけい') where byochu like '%体系%';
update $tmptbl set betsumei = replace(betsumei, '誘引', 'ゆういん') where byochu like '%誘引%';
update $tmptbl set betsumei = replace(betsumei, '交尾', 'こうび') where byochu like '%交尾%';
update $tmptbl set betsumei = replace(betsumei, '残渣', 'ざんさ') where byochu like '%残渣%';
update $tmptbl set betsumei = replace(betsumei, '作物', 'さくもつ') where byochu like '%作物%';
update $tmptbl set betsumei = replace(betsumei, '植物', 'しょくぶつ') where byochu like '%植物%';
update $tmptbl set betsumei = replace(betsumei, '野菜', 'やさい') where byochu like '%野菜%';
update $tmptbl set betsumei = replace(betsumei, '観葉', 'かんよう') where byochu like '%観葉%';
update $tmptbl set betsumei = replace(betsumei, '花梗', 'かこう') where byochu like '%花梗%';
update $tmptbl set betsumei = replace(betsumei, '花茎', 'かけい') where byochu like '%花茎%';
update $tmptbl set betsumei = replace(betsumei, '花径', 'かけい') where byochu like '%花径%';
update $tmptbl set betsumei = replace(betsumei, '黒節', 'くろふし') where byochu like '%黒節%';
update $tmptbl set betsumei = replace(betsumei, '暗色', 'あんしょく') where byochu like '%暗色%';
update $tmptbl set betsumei = replace(betsumei, '寄生', 'きせい') where byochu like '%寄生%';
update $tmptbl set betsumei = replace(betsumei, '移植', 'いしょく') where byochu like '%移植%';
update $tmptbl set betsumei = replace(betsumei, '定植', 'ていしょく') where byochu like '%定植%';
update $tmptbl set betsumei = replace(betsumei, '樹脂', 'じゅし') where byochu like '%樹脂%';
update $tmptbl set betsumei = replace(betsumei, '根重', 'こんじゅう') where byochu like '%根重%';
update $tmptbl set betsumei = replace(betsumei, '放射', 'ほうしゃ') where byochu like '%放射%';
update $tmptbl set betsumei = replace(betsumei, '裂果', 'れっか') where byochu like '%裂果%';
update $tmptbl set betsumei = replace(betsumei, '劣化', 'れっか') where byochu like '%劣化%';
update $tmptbl set betsumei = replace(betsumei, '漬物', 'つけもの') where byochu like '%漬物%';
update $tmptbl set betsumei = replace(betsumei, '小麦', 'こむぎ') where byochu like '%小麦%';
update $tmptbl set betsumei = replace(betsumei, '基部', 'きぶ') where byochu like '%基部%';
update $tmptbl set betsumei = replace(betsumei, '根物', 'ねもの') where byochu like '%根物%';
update $tmptbl set betsumei = replace(betsumei, '壌土', 'じょうど') where byochu like '%壌土%';
update $tmptbl set betsumei = replace(betsumei, '水稲', 'すいとう') where byochu like '%水稲%';
update $tmptbl set betsumei = replace(betsumei, '剥皮', 'はくひ') where byochu like '%剥皮%';
--ふりがな優先処理2
update $tmptbl set betsumei = replace(betsumei, '立', 'たち') where byochu like '%苗立枯%';
update $tmptbl set betsumei = replace(betsumei, '葉', 'は') where byochu like '%斑葉枯%';
update $tmptbl set betsumei = replace(betsumei, '植', 'うえ') where byochu like '%植いたみ%';
update $tmptbl set betsumei = replace(betsumei, '植', 'う') where byochu like '%植え%';
update $tmptbl set betsumei = replace(betsumei, '刈', 'か') where byochu like '%刈り%';
update $tmptbl set betsumei = replace(betsumei, '取', 'と') where byochu like '%取り%';
update $tmptbl set betsumei = replace(betsumei, '場', 'じょう') where byochu like '%ほ場%';
update $tmptbl set betsumei = replace(betsumei, '種', 'しゅ') where byochu like '%は種%';
--ふりがな優先処理3
update $tmptbl set betsumei = replace(betsumei, '変', 'ぺん') where byochu like '%褐変%';
update $tmptbl set betsumei = replace(betsumei, '斑', 'ぱん') where byochu like '%輪斑%' or byochu like '%褐斑%';
update $tmptbl set betsumei = replace(betsumei, '条', 'すじ') where byochu like '%黒条%';
update $tmptbl set betsumei = replace(betsumei, '腐', 'ふ') where byochu like '%腐らん%' or byochu like '%腐朽%';
update $tmptbl set betsumei = replace(betsumei, '腐', 'ぷ') where byochu like '%軟腐%' or byochu like '%乾腐%';
update $tmptbl set betsumei = replace(betsumei, '腐', 'ぐさ') where byochu like '%腐れ%';
update $tmptbl set betsumei = replace(betsumei, '汚', 'よご') where byochu like '%汚れ%';
update $tmptbl set betsumei = replace(betsumei, '亀', 'かめ') where byochu like '%亀%';
update $tmptbl set betsumei = replace(betsumei, '根', 'こん') where byochu like '%根朽%' or byochu like '%根茎%' or byochu like '%根部%' or byochu like '%根頭%';
update $tmptbl set betsumei = replace(betsumei, '茎', 'けい') where byochu like '%塊茎%' or byochu like '%根茎%' or byochu like '%鱗茎%';
update $tmptbl set betsumei = replace(betsumei, '苗', 'びょう') where byochu like '%幼苗%';
update $tmptbl set betsumei = replace(betsumei, '立', 'だち') where byochu like '%苗立%';
update $tmptbl set betsumei = replace(betsumei, '葉', 'よう') where byochu like '%変葉%' or byochu like '%斑葉%' or byochu like '%汚葉%' or byochu like '%縮葉%' or byochu like '%銀葉%';
update $tmptbl set betsumei = replace(betsumei, '実', 'じつ') where byochu like '%果実%' or byochu like '%結実%' or byochu like '%充実%';
update $tmptbl set betsumei = replace(betsumei, '色', 'いろ') where byochu like '%ごま色%' or byochu like '%灰色%';
update $tmptbl set betsumei = replace(betsumei, '褐', 'かつ') where byochu like '%褐条%' or byochu like '%褐紋%';
update $tmptbl set betsumei = replace(betsumei, '紫', 'し') where byochu like '%紫斑%';
update $tmptbl set betsumei = replace(betsumei, '緑', 'りょく') where byochu like '%緑斑%';
update $tmptbl set betsumei = replace(betsumei, '黒', 'こく') where byochu like '%黒斑%' or byochu like '%黒点%' or byochu like '%黒変%' or byochu like '%黒色%' or byochu like '%黒粒%' or byochu like '%黒とう%' or byochu like '%黒しゅ%';
update $tmptbl set betsumei = replace(betsumei, '白', 'はっ') where byochu like '%白化%';
update $tmptbl set betsumei = replace(betsumei, '白', 'はく') where byochu like '%白斑%' or byochu like '%白色%';
update $tmptbl set betsumei = replace(betsumei, '赤', 'せき') where byochu like '%赤斑%' or byochu like '%赤色%' or byochu like '%赤点%';
update $tmptbl set betsumei = replace(betsumei, '冬', 'とう') where byochu like '%冬期%';
update $tmptbl set betsumei = replace(betsumei, '大', 'たい') where byochu like '%大粒%';
update $tmptbl set betsumei = replace(betsumei, '野', 'の') where byochu like '%野ウサギ%';
update $tmptbl set betsumei = replace(betsumei, '木', 'ぎ') where byochu like '%ほだ木%';
update $tmptbl set betsumei = replace(betsumei, '合', 'ごう') where byochu like '%ゆ合%';
update $tmptbl set betsumei = replace(betsumei, '草', 'そう') where byochu like '%草%';
update $tmptbl set betsumei = replace(betsumei, '雑', 'ざっ') where byochu like '%雑%';
update $tmptbl set betsumei = replace(betsumei, '水', 'みず') where byochu like '%水腐%';
update $tmptbl set betsumei = replace(betsumei, '脱', 'だっ') where byochu like '%脱出%';
update $tmptbl set betsumei = replace(betsumei, '前', 'ぜん') where byochu like '%前作%';
--ふりがな通常処理
update $tmptbl set betsumei = replace(betsumei, '変', 'へん') where byochu like '%変%';
update $tmptbl set betsumei = replace(betsumei, '斑', 'はん') where byochu like '%斑%';
update $tmptbl set betsumei = replace(betsumei, '腐', 'ぐされ') where byochu like '%腐%';
update $tmptbl set betsumei = replace(betsumei, '枯', 'がれ') where byochu like '%枯%';
update $tmptbl set betsumei = replace(betsumei, '汚', 'お') where byochu like '%汚%';
update $tmptbl set betsumei = replace(betsumei, '条', 'じょう') where byochu like '%条%';
update $tmptbl set betsumei = replace(betsumei, '球', 'たま') where byochu like '%球%';
update $tmptbl set betsumei = replace(betsumei, '根', 'ね') where byochu like '%根%';
update $tmptbl set betsumei = replace(betsumei, '茎', 'くき') where byochu like '%茎%';
update $tmptbl set betsumei = replace(betsumei, '苗', 'なえ') where byochu like '%苗%';
update $tmptbl set betsumei = replace(betsumei, '立', 'たち') where byochu like '%立%';
update $tmptbl set betsumei = replace(betsumei, '葉', 'は') where byochu like '%葉%';
update $tmptbl set betsumei = replace(betsumei, '実', 'み') where byochu like '%実%';
update $tmptbl set betsumei = replace(betsumei, '花', 'はな') where byochu like '%花%';
update $tmptbl set betsumei = replace(betsumei, '先', 'さき') where byochu like '%先%';
update $tmptbl set betsumei = replace(betsumei, '色', 'しょく') where byochu like '%色%';
update $tmptbl set betsumei = replace(betsumei, '炭', 'すみ') where byochu like '%炭%';
update $tmptbl set betsumei = replace(betsumei, '褐', 'かっ') where byochu like '%褐%';
update $tmptbl set betsumei = replace(betsumei, '紫', 'むらさき') where byochu like '%紫%';
update $tmptbl set betsumei = replace(betsumei, '緑', 'みどり') where byochu like '%緑%';
update $tmptbl set betsumei = replace(betsumei, '黒', 'くろ') where byochu like '%黒%';
update $tmptbl set betsumei = replace(betsumei, '白', 'しろ') where byochu like '%白%';
update $tmptbl set betsumei = replace(betsumei, '赤', 'あか') where byochu like '%赤%';
update $tmptbl set betsumei = replace(betsumei, '冬', 'ふゆ') where byochu like '%冬%';
update $tmptbl set betsumei = replace(betsumei, '大', 'おお') where byochu like '%大%';
update $tmptbl set betsumei = replace(betsumei, '野', 'や') where byochu like '%野%';
update $tmptbl set betsumei = replace(betsumei, '形', 'けい') where byochu like '%形%';
update $tmptbl set betsumei = replace(betsumei, '木', 'もく') where byochu like '%木%';
update $tmptbl set betsumei = replace(betsumei, '国', 'ごく') where byochu like '%国%';
update $tmptbl set betsumei = replace(betsumei, '高', 'こう') where byochu like '%高%';
update $tmptbl set betsumei = replace(betsumei, '温', 'おん') where byochu like '%温%';
update $tmptbl set betsumei = replace(betsumei, '下', 'か') where byochu like '%下%';
update $tmptbl set betsumei = replace(betsumei, '水', 'すい') where byochu like '%水%';
update $tmptbl set betsumei = replace(betsumei, '麦', 'むぎ') where byochu like '%麦%';
update $tmptbl set betsumei = replace(betsumei, '抽', 'ちゅう') where byochu like '%抽%';
update $tmptbl set betsumei = replace(betsumei, '出', 'しゅつ') where byochu like '%出%';
update $tmptbl set betsumei = replace(betsumei, '基', 'もと') where byochu like '%基%';
update $tmptbl set betsumei = replace(betsumei, '種', 'たね') where byochu like '%種%';
update $tmptbl set betsumei = replace(betsumei, '起', 'き') where byochu like '%起%';
update $tmptbl set betsumei = replace(betsumei, '物', 'ぶつ') where byochu like '%物%';
update $tmptbl set betsumei = replace(betsumei, '除', 'じょ') where byochu like '%除%';
update $tmptbl set betsumei = replace(betsumei, '長', 'ちょう') where byochu like '%長%';
--ふりがな単一読み
update $tmptbl set betsumei = replace(betsumei, '作', 'さく') where byochu like '%作%';
update $tmptbl set betsumei = replace(betsumei, '次', 'じ') where byochu like '%次%';
update $tmptbl set betsumei = replace(betsumei, '時', 'じ') where byochu like '%時%';
update $tmptbl set betsumei = replace(betsumei, '類', 'るい') where byochu like '%類%';
update $tmptbl set betsumei = replace(betsumei, '等', 'とう') where byochu like '%等%';
update $tmptbl set betsumei = replace(betsumei, '性', 'せい') where byochu like '%性%';
update $tmptbl set betsumei = replace(betsumei, '害', 'がい') where byochu like '%害%';
update $tmptbl set betsumei = replace(betsumei, '幼', 'よう') where byochu like '%幼%';
update $tmptbl set betsumei = replace(betsumei, '成', 'せい') where byochu like '%成%';
update $tmptbl set betsumei = replace(betsumei, '内', 'ない') where byochu like '%内%';
update $tmptbl set betsumei = replace(betsumei, '病', 'びょう') where byochu like '%病%';
update $tmptbl set betsumei = replace(betsumei, '症', 'しょう') where byochu like '%症%';
update $tmptbl set betsumei = replace(betsumei, '損', 'そん') where byochu like '%損%';
update $tmptbl set betsumei = replace(betsumei, '障', 'しょう') where byochu like '%障%';
update $tmptbl set betsumei = replace(betsumei, '菌', 'きん') where byochu like '%菌%';
update $tmptbl set betsumei = replace(betsumei, '細', 'さい') where byochu like '%細%';
update $tmptbl set betsumei = replace(betsumei, '核', 'かく') where byochu like '%核%';
update $tmptbl set betsumei = replace(betsumei, '渋', 'しぶ') where byochu like '%渋%';
update $tmptbl set betsumei = replace(betsumei, '角', 'かく') where byochu like '%角%';
update $tmptbl set betsumei = replace(betsumei, '焼', 'やけ') where byochu like '%焼%';
update $tmptbl set betsumei = replace(betsumei, '網', 'あみ') where byochu like '%網%';
update $tmptbl set betsumei = replace(betsumei, '孔', 'こう') where byochu like '%孔%';
update $tmptbl set betsumei = replace(betsumei, '輪', 'りん') where byochu like '%輪%';
update $tmptbl set betsumei = replace(betsumei, '割', 'われ') where byochu like '%割%';
update $tmptbl set betsumei = replace(betsumei, '萎', 'い') where byochu like '%萎%';
update $tmptbl set betsumei = replace(betsumei, '縮', 'しゅく') where byochu like '%縮%';
update $tmptbl set betsumei = replace(betsumei, '凋', 'ちょう') where byochu like '%凋%';
update $tmptbl set betsumei = replace(betsumei, '朽', 'きゅう') where byochu like '%朽%';
update $tmptbl set betsumei = replace(betsumei, '軟', 'なん') where byochu like '%軟%';
update $tmptbl set betsumei = replace(betsumei, '乾', 'かん') where byochu like '%乾%';
update $tmptbl set betsumei = replace(betsumei, '膨', 'ぶくれ') where byochu like '%膨%';
update $tmptbl set betsumei = replace(betsumei, '折', 'おれ') where byochu like '%折%';
update $tmptbl set betsumei = replace(betsumei, '星', 'ほし') where byochu like '%星%';
update $tmptbl set betsumei = replace(betsumei, '化', 'か') where byochu like '%化%';
update $tmptbl set betsumei = replace(betsumei, '円', 'まる') where byochu like '%円%';
update $tmptbl set betsumei = replace(betsumei, '点', 'てん') where byochu like '%点%';
update $tmptbl set betsumei = replace(betsumei, '環', 'かん') where byochu like '%環%';
update $tmptbl set betsumei = replace(betsumei, '粒', 'りゅう') where byochu like '%粒%';
update $tmptbl set betsumei = replace(betsumei, '紋', 'もん') where byochu like '%紋%';
update $tmptbl set betsumei = replace(betsumei, '縞', 'しま') where byochu like '%縞%';
update $tmptbl set betsumei = replace(betsumei, '裸', 'はだか') where byochu like '%裸%';
update $tmptbl set betsumei = replace(betsumei, '入', 'いり') where byochu like '%入%';
update $tmptbl set betsumei = replace(betsumei, '苦', 'にが') where byochu like '%苦%';
update $tmptbl set betsumei = replace(betsumei, '舞', 'まい') where byochu like '%舞%';
update $tmptbl set betsumei = replace(betsumei, '空', 'くう') where byochu like '%空%';
update $tmptbl set betsumei = replace(betsumei, '微', 'び') where byochu like '%微%';
update $tmptbl set betsumei = replace(betsumei, '部', 'ぶ') where byochu like '%部%';
update $tmptbl set betsumei = replace(betsumei, '巣', 'す') where byochu like '%巣%';
update $tmptbl set betsumei = replace(betsumei, '頭', 'とう') where byochu like '%頭%';
update $tmptbl set betsumei = replace(betsumei, '眼', 'がん') where byochu like '%眼%';
update $tmptbl set betsumei = replace(betsumei, '塊', 'かい') where byochu like '%塊%';
update $tmptbl set betsumei = replace(betsumei, '鱗', 'りん') where byochu like '%鱗%';
update $tmptbl set betsumei = replace(betsumei, '片', 'ぺん') where byochu like '%片%';
update $tmptbl set betsumei = replace(betsumei, '羽', 'ぱ') where byochu like '%羽%';
update $tmptbl set betsumei = replace(betsumei, '感', 'かん') where byochu like '%感%';
update $tmptbl set betsumei = replace(betsumei, '伝', 'でん') where byochu like '%伝%';
update $tmptbl set betsumei = replace(betsumei, '染', 'せん') where byochu like '%染%';
update $tmptbl set betsumei = replace(betsumei, '疫', 'えき') where byochu like '%疫%';
update $tmptbl set betsumei = replace(betsumei, '穂', 'ほ') where byochu like '%穂%';
update $tmptbl set betsumei = replace(betsumei, '穎', 'えい') where byochu like '%穎%';
update $tmptbl set betsumei = replace(betsumei, '莢', 'さや') where byochu like '%莢%';
update $tmptbl set betsumei = replace(betsumei, '果', 'か') where byochu like '%果%';
update $tmptbl set betsumei = replace(betsumei, '米', 'まい') where byochu like '%米%';
update $tmptbl set betsumei = replace(betsumei, '心', 'しん') where byochu like '%心%';
update $tmptbl set betsumei = replace(betsumei, '芯', 'しん') where byochu like '%芯%';
update $tmptbl set betsumei = replace(betsumei, '芽', 'め') where byochu like '%芽%';
update $tmptbl set betsumei = replace(betsumei, '枝', 'えだ') where byochu like '%枝%';
update $tmptbl set betsumei = replace(betsumei, '軸', 'じく') where byochu like '%軸%';
update $tmptbl set betsumei = replace(betsumei, '株', 'かぶ') where byochu like '%株%';
update $tmptbl set betsumei = replace(betsumei, '胴', 'どう') where byochu like '%胴%';
update $tmptbl set betsumei = replace(betsumei, '幹', 'みき') where byochu like '%幹%';
update $tmptbl set betsumei = replace(betsumei, '皮', 'かわ') where byochu like '%皮%';
update $tmptbl set betsumei = replace(betsumei, '腰', 'こし') where byochu like '%腰%';
update $tmptbl set betsumei = replace(betsumei, '首', 'くび') where byochu like '%首%';
update $tmptbl set betsumei = replace(betsumei, '尻', 'しり') where byochu like '%尻%';
update $tmptbl set betsumei = replace(betsumei, '裏', 'うら') where byochu like '%裏%';
update $tmptbl set betsumei = replace(betsumei, '墨', 'すみ') where byochu like '%墨%';
update $tmptbl set betsumei = replace(betsumei, '銀', 'ぎん') where byochu like '%銀%';
update $tmptbl set betsumei = replace(betsumei, '灰', 'はい') where byochu like '%灰%';
update $tmptbl set betsumei = replace(betsumei, '黄', 'おう') where byochu like '%黄%';
update $tmptbl set betsumei = replace(betsumei, '紅', 'こう') where byochu like '%紅%';
update $tmptbl set betsumei = replace(betsumei, '青', 'あお') where byochu like '%青%';
update $tmptbl set betsumei = replace(betsumei, '雪', 'ゆき') where byochu like '%雪%';
update $tmptbl set betsumei = replace(betsumei, '早', 'そう') where byochu like '%早%';
update $tmptbl set betsumei = replace(betsumei, '晩', 'おそ') where byochu like '%晩%';
update $tmptbl set betsumei = replace(betsumei, '春', 'はる') where byochu like '%春%';
update $tmptbl set betsumei = replace(betsumei, '夏', 'なつ') where byochu like '%夏%';
update $tmptbl set betsumei = replace(betsumei, '秋', 'あき') where byochu like '%秋%';
update $tmptbl set betsumei = replace(betsumei, '前', 'まえ') where byochu like '%前%';
update $tmptbl set betsumei = replace(betsumei, '後', 'ご') where byochu like '%後%';
update $tmptbl set betsumei = replace(betsumei, '期', 'き') where byochu like '%期%';
update $tmptbl set betsumei = replace(betsumei, '短', 'たん') where byochu like '%短%';
update $tmptbl set betsumei = replace(betsumei, '小', 'しょう') where byochu like '%小%';
update $tmptbl set betsumei = replace(betsumei, '稲', 'いな') where byochu like '%稲%';
update $tmptbl set betsumei = replace(betsumei, '吊', 'つ') where byochu like '%吊り%';
update $tmptbl set betsumei = replace(betsumei, '半', 'はん') where byochu like '%半%';
update $tmptbl set betsumei = replace(betsumei, '身', 'しん') where byochu like '%身%';
update $tmptbl set betsumei = replace(betsumei, '甲', 'こう') where byochu like '%甲%';
update $tmptbl set betsumei = replace(betsumei, '材', 'ざい') where byochu like '%材%';
update $tmptbl set betsumei = replace(betsumei, '虫', 'ちゅう') where byochu like '%虫%';
update $tmptbl set betsumei = replace(betsumei, '蛾', 'が') where byochu like '%蛾%';
update $tmptbl set betsumei = replace(betsumei, '雄', 'おす') where byochu like '%雄%';
update $tmptbl set betsumei = replace(betsumei, '卵', 'らん') where byochu like '%卵%';
update $tmptbl set betsumei = replace(betsumei, '若', 'じゃく') where byochu like '%若%';
update $tmptbl set betsumei = replace(betsumei, '中', 'ちゅう') where byochu like '%中%';
update $tmptbl set betsumei = replace(betsumei, '齢', 'れい') where byochu like '%齢%';
update $tmptbl set betsumei = replace(betsumei, '未', 'み') where byochu like '%未%';
update $tmptbl set betsumei = replace(betsumei, '熟', 'じゅく') where byochu like '%熟%';
update $tmptbl set betsumei = replace(betsumei, '第', 'だい') where byochu like '%第%';
update $tmptbl set betsumei = replace(betsumei, '阻', 'そ') where byochu like '%阻%';
update $tmptbl set betsumei = replace(betsumei, '食', 'しょく') where byochu like '%食%';
update $tmptbl set betsumei = replace(betsumei, '息', 'そく') where byochu like '%息%';
update $tmptbl set betsumei = replace(betsumei, '生', 'せい') where byochu like '%生%';
update $tmptbl set betsumei = replace(betsumei, '育', 'いく') where byochu like '%育%';
update $tmptbl set betsumei = replace(betsumei, '不', 'ふ') where byochu like '%不%';
update $tmptbl set betsumei = replace(betsumei, '活', 'かっ') where byochu like '%活%';
update $tmptbl set betsumei = replace(betsumei, '着', 'ちゃく') where byochu like '%着%';
update $tmptbl set betsumei = replace(betsumei, '切', 'き') where byochu like '%切り%';
update $tmptbl set betsumei = replace(betsumei, '口', 'くち') where byochu like '%口%';
update $tmptbl set betsumei = replace(betsumei, '傷', 'きず') where byochu like '%傷%';
update $tmptbl set betsumei = replace(betsumei, '登', 'とう') where byochu like '%登%';
update $tmptbl set betsumei = replace(betsumei, '竹', 'たけ') where byochu like '%竹%';
update $tmptbl set betsumei = replace(betsumei, '牧', 'ぼく') where byochu like '%牧%';
update $tmptbl set betsumei = replace(betsumei, '藻', 'そう') where byochu like '%藻%';
update $tmptbl set betsumei = replace(betsumei, '一', 'いち') where byochu like '%一%';
update $tmptbl set betsumei = replace(betsumei, '多', 'た') where byochu like '%多%';
update $tmptbl set betsumei = replace(betsumei, '年', 'ねん') where byochu like '%年%';
update $tmptbl set betsumei = replace(betsumei, '科', 'か') where byochu like '%科%';
update $tmptbl set betsumei = replace(betsumei, '本', 'ほん') where byochu like '%本%';
update $tmptbl set betsumei = replace(betsumei, '畑', 'はた') where byochu like '%畑%';
update $tmptbl set betsumei = replace(betsumei, '地', 'ち') where byochu like '%地%';
update $tmptbl set betsumei = replace(betsumei, '湿', 'しつ') where byochu like '%湿%';
update $tmptbl set betsumei = replace(betsumei, '田', 'でん') where byochu like '%田%';
update $tmptbl set betsumei = replace(betsumei, '離', 'り') where byochu like '%離%';
update $tmptbl set betsumei = replace(betsumei, '帯', 'たい') where byochu like '%帯%';
update $tmptbl set betsumei = replace(betsumei, '東', 'とう') where byochu like '%東%';
update $tmptbl set betsumei = replace(betsumei, '関', 'かん') where byochu like '%関%';
update $tmptbl set betsumei = replace(betsumei, '海', 'かい') where byochu like '%海%';
update $tmptbl set betsumei = replace(betsumei, '山', 'ざん') where byochu like '%山%';
update $tmptbl set betsumei = replace(betsumei, '北', 'ほく') where byochu like '%北%';
update $tmptbl set betsumei = replace(betsumei, '型', 'がた') where byochu like '%型%';
update $tmptbl set betsumei = replace(betsumei, '陸', 'りく') where byochu like '%陸%';
update $tmptbl set betsumei = replace(betsumei, '南', 'みなみ') where byochu like '%南%';
update $tmptbl set betsumei = replace(betsumei, '効', 'こう') where byochu like '%効%';
update $tmptbl set betsumei = replace(betsumei, '土', 'ど') where byochu like '%土%';
update $tmptbl set betsumei = replace(betsumei, '子', 'し') where byochu like '%子%';
update $tmptbl set betsumei = replace(betsumei, '他', 'た') where byochu like '%他%';
update $tmptbl set betsumei = replace(betsumei, '諸', 'しょ') where byochu like '%諸%';
update $tmptbl set betsumei = replace(betsumei, '及', 'およ') where byochu like '%及び%';
update $tmptbl set betsumei = replace(betsumei, '含', 'ふく') where byochu like '%含む%';
update $tmptbl set betsumei = replace(betsumei, '除', 'のぞ') where byochu like '%除く%';
update $tmptbl set betsumei = replace(betsumei, '但', 'ただ') where byochu like '%但し%';
update $tmptbl set betsumei = replace(betsumei, '番', 'ばん') where byochu like '%番%';
update $tmptbl set betsumei = replace(betsumei, '摘', 'てき') where byochu like '%摘%';
update $tmptbl set betsumei = replace(betsumei, '全', 'ぜん') where byochu like '%全%';
update $tmptbl set betsumei = replace(betsumei, '幅', 'はば') where byochu like '%幅%';
update $tmptbl set betsumei = replace(betsumei, '罹', 'り') where byochu like '%罹%';
update $tmptbl set betsumei = replace(betsumei, '面', 'めん') where byochu like '%面%';
update $tmptbl set betsumei = replace(betsumei, '層', 'そう') where byochu like '%層%';
update $tmptbl set betsumei = replace(betsumei, '日', 'ひ') where byochu like '%日%';
update $tmptbl set betsumei = replace(betsumei, '柄', 'へい') where byochu like '%柄%';
update $tmptbl set betsumei = replace(betsumei, '房', 'ぼう') where byochu like '%房%';
update $tmptbl set betsumei = replace(betsumei, '率', 'りつ') where byochu like '%率%';
update $tmptbl set betsumei = replace(betsumei, '分', 'ぶん') where byochu like '%分%';
update $tmptbl set betsumei = replace(betsumei, '矮', 'わい') where byochu like '%矮%';
update $tmptbl set betsumei = replace(betsumei, '蕾', 'らい') where byochu like '%蕾%';
update $tmptbl set betsumei = replace(betsumei, '剪', 'せん') where byochu like '%剪%';
update $tmptbl set betsumei = replace(betsumei, '定', 'てい') where byochu like '%定%';
update $tmptbl set betsumei = replace(betsumei, '蒸', 'じょう') where byochu like '%蒸%';
update $tmptbl set betsumei = replace(betsumei, '散', 'さん') where byochu like '%散%';
update $tmptbl set betsumei = replace(betsumei, '寒', 'かん') where byochu like '%寒%';
update $tmptbl set betsumei = replace(betsumei, '干', 'かん') where byochu like '%干%';
update $tmptbl set betsumei = replace(betsumei, '時', 'じ') where byochu like '%時%';
update $tmptbl set betsumei = replace(betsumei, '発', 'はつ') where byochu like '%発%';
update $tmptbl set betsumei = replace(betsumei, '増', 'ぞう') where byochu like '%増%';
update $tmptbl set betsumei = replace(betsumei, '加', 'か') where byochu like '%加%';
update $tmptbl set betsumei = replace(betsumei, '進', 'しん') where byochu like '%進%';
update $tmptbl set betsumei = replace(betsumei, '数', 'すう') where byochu like '%数%';
update $tmptbl set betsumei = replace(betsumei, '梢', 'しょう') where byochu like '%梢%';
update $tmptbl set betsumei = replace(betsumei, '収', 'しゅう') where byochu like '%収%';
update $tmptbl set betsumei = replace(betsumei, '穫', 'かく') where byochu like '%穫%';
update $tmptbl set betsumei = replace(betsumei, '量', 'りょう') where byochu like '%量%';
update $tmptbl set betsumei = replace(betsumei, '密', 'みつ') where byochu like '%密%';
update $tmptbl set betsumei = replace(betsumei, '糖', 'とう') where byochu like '%糖%';
update $tmptbl set betsumei = replace(betsumei, '度', 'ど') where byochu like '%度%';
update $tmptbl set betsumei = replace(betsumei, '低', 'てい') where byochu like '%低%';
update $tmptbl set betsumei = replace(betsumei, '減', 'げん') where byochu like '%減%';
update $tmptbl set betsumei = replace(betsumei, '少', 'しょう') where byochu like '%少%';
update $tmptbl set betsumei = replace(betsumei, '完', 'かん') where byochu like '%完%';
update $tmptbl set betsumei = replace(betsumei, '初', 'しょ') where byochu like '%初%';
update $tmptbl set betsumei = replace(betsumei, '副', 'ふく') where byochu like '%副%';
update $tmptbl set betsumei = replace(betsumei, '浮', 'うき') where byochu like '%浮%';
update $tmptbl set betsumei = replace(betsumei, '薬', 'やく') where byochu like '%薬%';
update $tmptbl set betsumei = replace(betsumei, '展', 'てん') where byochu like '%展%';
update $tmptbl set betsumei = replace(betsumei, '銅', 'どう') where byochu like '%銅%';
update $tmptbl set betsumei = replace(betsumei, '和', 'わ') where byochu like '%和%';
update $tmptbl set betsumei = replace(betsumei, '剤', 'ざい') where byochu like '%剤%';
update $tmptbl set betsumei = replace(betsumei, '飛', 'ひ') where byochu like '%飛%';
update $tmptbl set betsumei = replace(betsumei, '有', 'ゆう') where byochu like '%有%';
update $tmptbl set betsumei = replace(betsumei, '無', 'む') where byochu like '%無%';
update $tmptbl set betsumei = replace(betsumei, '機', 'き') where byochu like '%機%';
update $tmptbl set betsumei = replace(betsumei, '古', 'ふる') where byochu like '%古%';
update $tmptbl set betsumei = replace(betsumei, '回', 'かい') where byochu like '%回%';
update $tmptbl set betsumei = replace(betsumei, '親', 'おや') where byochu like '%親%';
update $tmptbl set betsumei = replace(betsumei, '非', 'ひ') where byochu like '%非%';
update $tmptbl set betsumei = replace(betsumei, '液', 'えき') where byochu like '%液%';
update $tmptbl set betsumei = replace(betsumei, '充', 'じゅう') where byochu like '%充%';
update $tmptbl set betsumei = replace(betsumei, '又', 'また') where byochu like '%又%';
update $tmptbl set betsumei = replace(betsumei, '状', 'じょう') where byochu like '%状%';
update $tmptbl set betsumei = replace(betsumei, '用', 'よう') where byochu like '%用%';
update $tmptbl set betsumei = replace(betsumei, '砂', 'さ') where byochu like '%砂%';
update $tmptbl set betsumei = replace(betsumei, '因', 'いん') where byochu like '%因%';
update $tmptbl set betsumei = replace(betsumei, '被', 'ひ') where byochu like '%被%';
update $tmptbl set betsumei = replace(betsumei, '茶', 'ちゃ') where byochu like '%茶%';
--別名処理
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'おそぐされ', 'ばんぷ')) where byochu like '%晩腐%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'まるはん', 'えんぱん')) where byochu like '%円斑%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ふたおびこやが', 'いねあおむし')) where byochu like '%フタオビコヤガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'いねつとむし', 'いちもんじせせり')) where byochu like '%イネツトムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ちゅう', 'が')) where byochu like '%ニカメイチュウ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'どろおいむし', 'くびほそはむし')) where byochu like '%イネドロオイムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'から', 'きもぐり')) where byochu like '%イネカラバエ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ひめはもぐり', 'みぎり')) where byochu like '%イネヒメハモグリバエ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'すくみりんごがい', 'じゃんぼたにし')) where byochu like '%スクミリンゴガイ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'だいめいちゅう', 'いねよとう')) where byochu like 'ダイメイチュウ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'うり', 'わたへりくろ')) where byochu like '%ウリノメイガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'はむし', 'ばえ')) where byochu like '%ウリハムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'あおむし', 'もんしろちょう')) where byochu like 'アオムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'はいまだらのめいが', 'だいこんしんくいむし')) where byochu like '%ハイマダラノメイガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'だいこんしんくいむし', 'はいまだらのめいが')) where byochu like '%ダイコンシンクイムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'いもこが', 'いもきばが')) where byochu like '%イモコガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ほそが', 'さんかくはまき')) where byochu like '%チャノホソガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'くわのめいが', 'すきむし')) where byochu like '%クワノメイガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'もんしろどくが', 'くわのきんけむし')) where byochu like '%モンシロドクガ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'くわのきんけむし', 'もんしろどくが')) where byochu like '%クワノキンケムシ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ひめこしんくい', 'くわのこきくいむし')) where byochu like '%ヒメコシンクイ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'しめの', 'のしめ')) where byochu like '%シメノマダラメイガ%'; --2025.10.17追加
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'やそ', 'のねずみ')) where byochu like '%野ソ%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'えきが', 'わきめ')) where byochu like '%腋芽%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'そくが', 'わきめ')) where byochu like '%側芽%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'てきか', 'てっか')) where byochu like '%摘果%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'ちゃくはな', 'ちゃっか')) where byochu like '%着花%';
update $tmptbl set betsumei = concat('、', betsumei, replace(betsumei, 'こうよう', 'ひろは')) where byochu like '%広葉%';
--あいまい検索ルビ 2023.2.3
update $tmptbl set betsumei = concat('、', betsumei, fuzzy(betsumei));
commit;
begin transaction;
drop table if exists $tgtbl;
create temp table $tgtbl (cid integer, gid integer, gname varchar unique);
--害虫
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'アオムシ'), 'アオムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%アゲハ'), 'アゲハＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%アザミウマ'), 'アザミウマＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ネ|イガ)アブラムシ$'), 'アブラムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!シロ)アリ$'), 'アリＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%イナゴ'), 'イナゴ・バッタＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%イラガ'), 'イラガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ウスバ'), 'ウスバＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ウワバ'), 'ウワバＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ウンカ'), 'ウンカＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!コナ|ロウ)カイガラムシ$'), 'カイガラムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%カキノヘタムシガ'), 'カキノヘタムシガ・マイコガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ウスモンミドリ)カスミカメ$'), 'カスミカメＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ハラアカ)マイマイ$'), 'カタツムリ・マイマイＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%カブトムシ%'), 'カブトムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%カミキリ'), 'カミキリムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ナガ)カメムシ$'), 'カメムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%カレハ'), 'カレハガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ガガンボ'), 'ガガンボＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%キクイムシ'), 'キクイムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%キジラミ'), 'キジラミＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%キバチ'), 'キバチＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%クスサン'), 'クスサンＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%クロバネキノコバエ'), 'クロバネキノコバエＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%グンバイ'), 'グンバイムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ケシキスイ'), 'ケシキスイＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like 'ケムシ%'), 'ケムシＧ'); --2025.10.17修正
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'ケラ'), 'ケラＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コウモリガ'), 'コウモリガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コオロギ'), 'コオロギ・カネタタキＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コガネ'), 'コガネムシ・ブイブイＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'ネギコガ'), 'コガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!キュウコン)コナカイガラムシ$'), 'コナカイガラムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'コナガ'), 'コナガ・スガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コナジラミ'), 'コナジラミＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コナダニ'), 'コナダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%コメツキ'), 'コメツキムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ブドウ)サビダニ$'), 'サビダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%シジミ'), 'シジミチョウＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%シバンムシ'), 'シバンムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%エダシャク'), 'シャクガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%シャチホコ'), 'シャチホコガ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'ジャガイモガ'), 'ジャガイモガ・イモコガ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%シロアリ'), 'シロアリＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'ナシヒメシンクイ'), 'シンクイガ・シンクイムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%スカシバ'), 'スカシバＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and (byochu like '%スズメ' and byochu <> 'スズメ')), 'スズメガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ゼミ'), 'セミＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%センチュウ'), 'センチュウＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu = 'イネミズゾウムシ'), 'ゾウムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タネコバチ'), 'タネコバチＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タネバエ'), 'タネバエ・ハナバエＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タマバエ'), 'タマバエＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タマバチ'), 'タマバチＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タマムシ'), 'タマムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ワタムシ'), 'タマワタムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ダンゴムシ'), 'ダンゴムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%チビガ'), 'チビガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%チョッキリ%'), 'チョッキリＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ツトガ'), 'ツトガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu regexp '(?<!ニジュウヤホシ)テントウ$'), 'テントウムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ニジュウヤホシテントウ'), 'テントウムシダマシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%トビムシ'), 'トビムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%トラガ'), 'トラガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%トリバ'), 'トリバＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ナガカメムシ'), 'ナガカメムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like 'ナメクジ%'), 'ナメクジＧ'); --2025.10.17修正
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ネアブラムシ'), 'ネアブラムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ネダニ'), 'ネダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハゴロモ'), 'ハゴロモＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハダニ'), 'ハダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハバチ'), 'ハバチＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハマキ'), 'ハマキＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハムシ'), 'ハムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハモグリガ'), 'ハモグリガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%モグリバエ'), 'ハモグリバエ・キモグリバエ・カラバエ・ミギワバエＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハンミョウ'), 'ハンミョウＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ヒトリ'), 'ヒトリガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ヒラタムシ'), 'ヒラタムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ヒロズコガ'), 'ヒロズコガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ホコリダニ'), 'ホコリダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ホソガ'), 'ホソガ・カワモグリＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ドクガ'), 'マイマイガ・ドクガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ミノガ'), 'ミノガ・ミノムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ミバエ'), 'ミバエＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ムギダニ'), 'ムギダニＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%メイチュウ'), 'メイガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%タバコガ'), 'ヤガＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ヨコバイ'), 'ヨコバイＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ヨトウ'), 'ヨトウＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%リンゴガイ'), 'リンゴガイＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ロウムシ'), 'ロウムシ・ロウカイガラムシＧ');
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ハモグリダニ'), 'ハモグリダニＧ'); --2025.10.17追加
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ツツミノガ'), 'ツツミノガＧ'); --2025.10.17追加
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%キバガ'), 'キバガＧ'); --2025.10.17追加
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like 'コクゾウ%'), '貯穀・貯蔵害虫'); --2025.10.17修正
insert into $tgtbl (cid, gid, gname) values (2, (select distinct gid from $tmptbl where cid = 2 and byochu like '%ザリガニ'), 'その他の害虫');
--雑草
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu = 'ノビエ'), '水田一年生雑草');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu = 'ウリカワ'), '水田多年生雑草');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu = 'スズメノテッポウ'), '一年生雑草');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu like 'ササ%'), '多年生雑草');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu like '%藻%'), '藻類、ウキクサ、コケ類');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu like '%かん木'), 'かん木');
insert into $tgtbl (cid, gid, gname) values (3, (select distinct gid from $tmptbl where cid = 3 and byochu like 'アゼガヤ%'), 'その他の雑草');
--鳥獣例外処理
insert into $tgtbl (cid, gid, gname) values (4, (select distinct gid from $tmptbl where cid = 2 and byochu in ('イノシシ', 'ウソ', 'カモシカ', 'カラス')), '鳥獣');
update $tmptbl set cid = 4, idbyochu = idbyochu + 20000000 where cid = 2 and gid in (select gid from $tgtbl where gname = '鳥獣');
--ブドウサビダニ例外処理
update $tmptbl set idbyochu = (select max(idbyochu) from $tmptbl where cid = 2 and gid in (select gid from $tgtbl where gname = 'サビダニＧ')) + 100  where byochu = 'ブドウサビダニ';
update $tmptbl set gid = (select gid from $tgtbl where gname = 'サビダニＧ')  where byochu = 'ブドウサビダニ';
--ブドウヒメハダニ例外処理 2025.10.17追加
update $tmptbl set idbyochu = (select max(idbyochu) from $tmptbl where cid = 2 and gid in (select gid from $tgtbl where gname = 'ハダニＧ')) + 100  where byochu = 'ブドウヒメハダニ';
update $tmptbl set gid = (select gid from $tgtbl where gname = 'ハダニＧ')  where byochu = 'ブドウヒメハダニ';
--複合害虫例外処理 2025.10.17追加
update $tmptbl set (gid, idbyochu) = (990, '2990'||substr(idbyochu, 5)) where cid = 2 and gid = (select gid from $tgtbl where gname = '貯穀・貯蔵害虫') and byochu like '%カイガラムシ%';
insert into $tgtbl (cid, gid, gname) values (2, 990, '複合害虫');
--貯穀・貯蔵害虫の gid 変更 2025.10.17追加
update $tmptbl set (gid, idbyochu) = (980, '2980'||substr(idbyochu, 5)) where cid = 2 and gid = (select gid from $tgtbl where gname = '貯穀・貯蔵害虫');
update $tgtbl set gid = 980 where cid = 2 and gid = (select gid from $tgtbl where gname = '貯穀・貯蔵害虫');
delete from $tgtbl where gid is null;
commit;
/* 検索用病害虫マスター (2014.01.15) */
begin transaction;
drop table if exists $mastbl;
create table $mastbl (cid integer, gid integer, idbyochu varchar primary key, byochu varchar unique, betsumei varchar);
insert or ignore into $mastbl (cid, gid, idbyochu, byochu, betsumei) select cid, gid, idbyochu, byochu, betsumei from $tmptbl where cid = 1 order by betsumei;
insert or ignore into $mastbl (cid, gid, idbyochu, byochu, betsumei) select cid, gid, idbyochu, byochu, betsumei from $tmptbl left join $tgtbl using(cid, gid) where cid = 2 order by gid, idbyochu;
insert or ignore into $mastbl (cid, gid, idbyochu, byochu, betsumei) select cid, gid, idbyochu, byochu, betsumei from $tmptbl left join $tgtbl using(cid, gid) where cid = 3 order by gid, betsumei;
insert or ignore into $mastbl (cid, gid, idbyochu, byochu, betsumei) select cid, gid, idbyochu, byochu, betsumei from $tmptbl where cid = 4 order by betsumei;
insert or ignore into $mastbl (cid, gid, idbyochu, byochu, betsumei) select cid, gid, idbyochu, byochu, betsumei from $tmptbl where cid = 5 order by betsumei;
commit;
create index idxMByochuBetsumei on $mastbl (betsumei);
drop table if exists $tmptbl;
/* 病害虫選択ダイアログボックス用病害虫マスター (2014.01.15) */
begin transaction;
drop table if exists $dlgtbl;
create table $dlgtbl (cid integer, gid integer, idbyochu varchar primary key, byochu varchar unique, betsumei varchar);
insert into $dlgtbl select cid, gid, idbyochu, byochu, betsumei from $mastbl where byochu not regexp '除く|北海道|東北|北陸|関東|東山|東海|近畿|中国|四国|九州';
commit;
create index idxByochuBetsumei on $dlgtbl (betsumei);
/* 病害虫カテゴリマスター (2012.05.09) */
begin transaction;
drop table if exists $cattbl;
create table $cattbl (cid integer primary key, cname varchar unique);
insert into $cattbl values(1, '病害');
insert into $cattbl values(2, '害虫');
insert into $cattbl values(3, '雑草');
insert into $cattbl values(4, '鳥獣');
insert into $cattbl values(5, 'その他');
commit;
/* 病害虫グループマスター (2014.01.12) */
begin transaction;
drop table if exists $grptbl;
create table $grptbl (cid integer, gid integer, gname varchar primary key);
insert into $grptbl select * from $tgtbl;
commit;\n
BYOCHU2;

if ($sqlonly) {
  echo mb_convert_encoding($query, 'SJIS-win', 'UTF-8');
  return 1;
}

$res = $db->exec($query);
if ($res === false) {
  $err = $db->errorInfo();
  logputs("acis: byochu", $err[2], 'Cron DB Error');
  if ($debug) echo "acis: byochu: $err[2]\n";
  return 0;
}

$sql = <<<BYOCHU3
--/d
/* $date 現在の農水省農薬登録情報提供システムに基づく病害虫・雑草マスター (2021.05.10) */
/* 検索用病害虫マスター 2014.01.15 */
begin transaction;
drop table if exists $mastbl;
create table $mastbl (cid integer, gid integer, idbyochu varchar primary key, byochu varchar unique, betsumei varchar);\n
BYOCHU3;

$res = $db->query("select * from $mastbl");
if ($res === false) {
  $err = $db->errorInfo();
  logputs("acis: byochu", $err[2], 'Cron DB Error');
  if ($debug) echo "acis: byochu: $err[2]\n";
  return 0;
}
while ($rec = $res->fetch(PDO::FETCH_NUM)) {
  $sql .= sprintf("insert into $mastbl values(%d, %d, '%s', '%s', '%s');\n", $rec[0], $rec[1], $rec[2], $rec[3], $rec[4]);
}
dbCloseStatement($res);

$sql .= <<<BYOCHU4
commit;
create index idxMByochuBetsumei on $mastbl (betsumei);
/* 病害虫選択ダイアログボックス用病害虫マスター (2020.05.10) */
begin transaction;
drop table if exists $dlgtbl;
create table $dlgtbl (cid integer, gid integer, idbyochu varchar primary key, byochu varchar unique, betsumei varchar);
insert into $dlgtbl select cid, gid, idbyochu, byochu, betsumei from $mastbl where byochu not regexp '除く|北海道|東北|北陸|関東|東山|東海|近畿|中国|四国|九州';
commit;
create index idxByochuBetsumei on $dlgtbl (betsumei);\n
/* 病害虫カテゴリマスター (2012.05.09) */
begin transaction;
drop table if exists $cattbl;
create table $cattbl (cid integer primary key, cname varchar unique);
insert into $cattbl values(1, '病害');
insert into $cattbl values(2, '害虫');
insert into $cattbl values(3, '雑草');
insert into $cattbl values(4, '鳥獣');
insert into $cattbl values(5, 'その他');
commit;
/* 病害虫グループマスター (2014.01.15) */
begin transaction;
drop table if exists $grptbl;
create table $grptbl (cid integer, gid integer, gname varchar primary key);\n
BYOCHU4;

$res = $db->query("select * from $grptbl");
while ($rec = $res->fetch(PDO::FETCH_NUM)) {
  $sql .= sprintf("insert into $grptbl values(%d, %d, '%s');\n", $rec[0], $rec[1], $rec[2]);
}
dbCloseStatement($res);
$sql .= "commit;\n";
file_put_contents("$datdir/$massql", mb_convert_encoding($sql, 'SJIS-win', 'UTF-8'), LOCK_EX);

$time += microtime(true);
logputs('acis: byochu', "Created $time");
if ($debug) echo "acis: byochu: Created $time\n";
return 1;
?>
